In [ ]:
# create the directory structure
!mkdir -p MLChurn/data/raw
!mkdir -p MLChurn/data/procesed
!mkdir -p MLChurn/src
# MLChurn/data/raw - capture the raw data
# MLChurn/data/procesed - store clean data
# MLChurn/src - store code files

# create empty files
!touch MLChurn/src/ingest.py
!touch MLChurn/src/preprocess.py
!touch MLChurn/src/train.py

In [ ]:
!ls -R MLChurn

MLChurn:
data  src

MLChurn/data:
procesed  raw

MLChurn/data/procesed:

MLChurn/data/raw:

MLChurn/src:
ingest.py  preprocess.py  train.py

In [ ]:
!touch MLChurn/requirements.txt

In [ ]:
%%writefile /content/MLChurn/requirements.txt
mlflow
pyngrok

Overwriting /content/MLChurn/requirements.txt

In [ ]:
!cat MLChurn/requirements.txt

mlflow
pyngrok

In [ ]:
%%writefile /content/MLChurn/src/ingest.py

# to collect the data and store it in our location for further use
def ingest_data():
  import pandas as pd
  data_src = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"
  data_dest = "/content/MLChurn/data/raw/"

  df = pd.read_csv(data_src)
  #print(df.head(2))
  df.to_csv(data_dest+'data.csv',index=False)
  print('Data ingestion completed. check folder /content/MLChurn/data/raw')

if __name__ == "__main__":
  ingest_data()

Overwriting /content/MLChurn/src/ingest.py

In [ ]:
!python MLChurn/src/ingest.py

In [ ]:
%%writefile /content/MLChurn/src/preprocess.py

def preprocess_data():
  # set the source and destination path
  import pandas as pd
  data_src = '/content/MLChurn/data/raw'
  data_dest = '/content/MLChurn/data/procesed'

  # load data from source
  df = pd.read_csv(data_src+'/data.csv')
  #print(df.shape)
  #print(df.info())
  #print(df.head(1))

  # to mark the features to ignore for preprocess
  ign_cols = ['customerID','Churn']
  #print(ign_cols)

  # find the category and numerical columns
  cat_cols = df.drop(ign_cols,axis=1).select_dtypes(include='object').columns
  #print(cat_cols)
  num_cols = df.drop(ign_cols,axis=1).select_dtypes(exclude='object').columns
  #print(num_cols)

  #print(len(cat_cols), len(num_cols))

  # check null value and fix it using mean for numeric value and mode for categorical value
  if df[cat_cols].isnull().sum().any():
    df[cat_cols].fillna(df[cat_cols].mode())

  if df[num_cols].isnull().sum().any():
    df[num_cols].fillna(df[num_cols].mean())

  # check and convert target value to numerical
  #print(df['Churn'].unique())
  df['Churn'] = df['Churn'].map({'No':0,'Yes':1})
  #print(df['Churn'].unique())

  # do category encoding
  df_enc = pd.get_dummies(df[cat_cols],columns=cat_cols,drop_first=True,dtype=int)
  #print(df_enc.shape)
  #print(df_enc.head(1))
  #print(df_enc.info())

  # concat all the non-encoded(num_cols)+tgt_cols
  df_new = pd.concat([df[num_cols],df_enc,df['Churn']],axis=1)

  df_new.to_csv(data_dest+'/preprcessed_data.csv',index=False)
  print('Data preprocessing completed.  check folder /content/MLChurn/data/procesed')

if __name__ == "__main__":
  preprocess_data()

Overwriting /content/MLChurn/src/preprocess.py

In [ ]:
%%writefile /content/MLChurn/src/train.py

def train_model():
  import mlflow
  import sqlite3
  import pandas as pd
  from sklearn.model_selection import train_test_split
  from sklearn.linear_model import LogisticRegression
  from sklearn.metrics import accuracy_score, f1_score
  from sklearn.tree import DecisionTreeClassifier

  # store tracking info in a light weight db called sqlite
  MLFLOW_TRACKING_URI = 'sqlite:///myprojflow.db'
  mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
  experiment = mlflow.set_experiment('Customer churn Classification')
  print(experiment.name)

  #experiment = mlflow.set_experiment('Customer churn Classification')
  #print(experiment.name)
  print(experiment.experiment_id)

  data_src = '/content/MLChurn/data/procesed/'
  df = pd.read_csv(data_src+'preprcessed_data.csv',nrows=100)

  print(df.shape)
  print(df.head(1))
  #print(df.info())

  X = df.drop('Churn',axis=1)
  y = df['Churn']

  X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=42)
  print(X_train.shape,X_val.shape,y_train.shape,y_val.shape)

  run_name = 'LR L2'
  lm_name = 'lm '+run_name
  with mlflow.start_run(experiment_id = experiment.experiment_id,run_name=run_name ):
    #model = LogisticRegression(penalty='l2', solver='lbfgs',max_iter=90)
    #model = LogisticRegression(penalty='l1',solver='saga',max_iter=50)

    model.fit(X_train,y_train)

    pred = model.predict(X_val)
    acc = accuracy_score(y_val,pred)
    f1 = f1_score(y_val,pred)

    #print(acc)
    #print(f1)
    mlflow.log_param('model',run_name)
    print(model)
    if isinstance(model, DecisionTreeClassifier):
      mlflow.log_param('max_depth',model.max_depth)
    elif isinstance(model, LogisticRegression):
      mlflow.log_param('penalty',model.penalty)
      mlflow.log_param('max_iter',model.max_iter)

    mlflow.log_metric('f1_score',f1)
    mlflow.log_metric('acc_score',acc)
    mlflow.sklearn.log_model(model,"model")
if __name__ == "__main__":
  train_model()

Overwriting /content/MLChurn/src/train.py

In [ ]:
!pip install -r /content/MLChurn/requirements.txt

Collecting mlflow (from -r /content/MLChurn/requirements.txt (line 1))
  Downloading mlflow-3.9.0-py3-none-any.whl.metadata (31 kB)
Collecting pyngrok (from -r /content/MLChurn/requirements.txt (line 2))
  Downloading pyngrok-7.5.0-py3-none-any.whl.metadata (8.1 kB)
Collecting mlflow-skinny==3.9.0 (from mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading mlflow_skinny-3.9.0-py3-none-any.whl.metadata (32 kB)
Collecting mlflow-tracing==3.9.0 (from mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading mlflow_tracing-3.9.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.18.1)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow->-r /content/MLChurn/requirements.txt (line 1)) (43.0.3)
Collecting docker<8,>=4.0.0 (from mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<24 (from mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading gunicorn-23.0.0-py3-none-any.whl.metadata (4.4 kB)
Collecting huey<3,>=2.5.4 (from mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: pyarrow<23,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow->-r /content/MLChurn/requirements.txt (line 1)) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.16.3)
Collecting skops<1 (from mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading skops-0.13.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.0.46)
Requirement already satisfied: cachetools<7,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading databricks_sdk-0.82.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.123.10)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.37.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.37.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.37.0)
Requirement already satisfied: packaging<26 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (25.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (5.29.5)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.2.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.40.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.3.10)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<47,>=43.0.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.1.5)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading graphql_core-3.2.7-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow->-r /content/MLChurn/requirements.txt (line 1))
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.3.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.47.0)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.23.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.58b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.58b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.5.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (2026.1.4)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (5.0.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (4.9.1)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette<0.51.0,>=0.40.0->fastapi<1->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (4.12.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.9.0->mlflow->-r /content/MLChurn/requirements.txt (line 1)) (0.6.2)
Downloading mlflow-3.9.0-py3-none-any.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 68.8 MB/s eta 0:00:00
Downloading mlflow_skinny-3.9.0-py3-none-any.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 85.3 MB/s eta 0:00:00
Downloading mlflow_tracing-3.9.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 62.5 MB/s eta 0:00:00
Downloading pyngrok-7.5.0-py3-none-any.whl (24 kB)
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 10.8 MB/s eta 0:00:00
Downloading flask_cors-6.0.2-py3-none-any.whl (13 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 7.5 MB/s eta 0:00:00
Downloading gunicorn-23.0.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.0/85.0 kB 5.7 MB/s eta 0:00:00
Downloading huey-2.6.0-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.0/77.0 kB 5.1 MB/s eta 0:00:00
Downloading skops-0.13.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.2/131.2 kB 10.0 MB/s eta 0:00:00
Downloading databricks_sdk-0.82.0-py3-none-any.whl (789 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 789.2/789.2 kB 43.2 MB/s eta 0:00:00
Downloading graphql_core-3.2.7-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 15.6 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Installing collected packages: huey, pyngrok, gunicorn, graphql-core, graphql-relay, docker, skops, graphene, Flask-CORS, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
Successfully installed Flask-CORS-6.0.2 databricks-sdk-0.82.0 docker-7.1.0 graphene-3.4.3 graphql-core-3.2.7 graphql-relay-3.2.0 gunicorn-23.0.0 huey-2.6.0 mlflow-3.9.0 mlflow-skinny-3.9.0 mlflow-tracing-3.9.0 pyngrok-7.5.0 skops-0.13.0

In [ ]:
import mlflow
# store tracking info in a light weight db called sqlite
MLFLOW_TRACKING_URI = 'sqlite:///myprojflow.db'
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
experiment = mlflow.set_experiment('Customer churn Classification')
print(experiment.name)

2026/02/01 03:26:22 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.schemas
2026/02/01 03:26:22 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.tables
2026/02/01 03:26:22 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.types
2026/02/01 03:26:22 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.constraints
2026/02/01 03:26:22 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.defaults
2026/02/01 03:26:22 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.comments
2026/02/01 03:26:22 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/02/01 03:26:22 INFO mlflow.store.db.utils: Updating database tables
2026/02/01 03:26:22 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2026/02/01 03:26:22 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade  -> 451aebb31d03, add metric step
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
2026/02/01 03:26:23 INFO alembic.runtime.migration: Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade f5a4f2784254 -> 0584bdc529eb, add cascading deletion to datasets from experiments
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade 0584bdc529eb -> 400f98739977, add logged model tables
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade 400f98739977 -> 6953534de441, add step to inputs table
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade 6953534de441 -> bda7b8c39065, increase_model_version_tag_value_limit
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade bda7b8c39065 -> cbc13b556ace, add V3 trace schema columns
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade cbc13b556ace -> 770bee3ae1dd, add assessments table
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade 770bee3ae1dd -> a1b2c3d4e5f6, add spans table
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade a1b2c3d4e5f6 -> de4033877273, create entity_associations table
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade de4033877273 -> 1a0cddfcaa16, Add webhooks and webhook_events tables
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade 1a0cddfcaa16 -> 534353b11cbc, add scorer tables
2026/02/01 03:26:24 INFO alembic.runtime.migration: Running upgrade 534353b11cbc -> 71994744cf8e, add evaluation datasets
2026/02/01 03:26:25 INFO alembic.runtime.migration: Running upgrade 71994744cf8e -> 3da73c924c2f, add outputs to dataset record
2026/02/01 03:26:25 INFO alembic.runtime.migration: Running upgrade 3da73c924c2f -> bf29a5ff90ea, add jobs table
2026/02/01 03:26:25 INFO alembic.runtime.migration: Running upgrade bf29a5ff90ea -> 1bd49d398cd23, add secrets tables
2026/02/01 03:26:25 INFO alembic.runtime.migration: Running upgrade 1bd49d398cd23 -> b7c8d9e0f1a2, add trace metrics table
2026/02/01 03:26:25 INFO alembic.runtime.migration: Running upgrade b7c8d9e0f1a2 -> 5d2d30f0abce, update job table
2026/02/01 03:26:25 INFO alembic.runtime.migration: Running upgrade 5d2d30f0abce -> c9d4e5f6a7b8, add routing strategy to endpoints and linkage type to mappings
2026/02/01 03:26:25 INFO alembic.runtime.migration: Running upgrade c9d4e5f6a7b8 -> 2c33131f4dae, add online_scoring_configs table
2026/02/01 03:26:25 INFO alembic.runtime.migration: Running upgrade 2c33131f4dae -> d3e4f5a6b7c8, add display_name to endpoint_bindings
2026/02/01 03:26:25 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2026/02/01 03:26:25 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2026/02/01 03:26:25 INFO mlflow.tracking.fluent: Experiment with name 'Customer churn Classification' does not exist. Creating a new experiment.

Customer churn Classification

In [ ]:
import sys
sys.path.append('/content/MLChurn/src') # /content/MLChurn/src
#from MLChurn.src.ingest import ingest_data
import ingest
import preprocess
import train

# to reload the model into current session memory
import importlib
importlib.reload(ingest)
importlib.reload(preprocess)
importlib.reload(train)

# calling/using the method from the module
ingest.ingest_data()
preprocess.preprocess_data()
train.train_model()

Data ingestion completed. check folder /content/MLChurn/data/raw
Data preprocessing completed.  check folder /content/MLChurn/data/procesed
Customer churn Classification
1
(100, 6560)
   SeniorCitizen  tenure  MonthlyCharges  gender_Male  Partner_Yes  \
0              0       1           29.85            0            1

   Dependents_Yes  PhoneService_Yes  MultipleLines_No phone service  \
0               0                 0                               1

   MultipleLines_Yes  InternetService_Fiber optic  ...  TotalCharges_996.45  \
0                  0                            0  ...                    0

   TotalCharges_996.85  TotalCharges_996.95  TotalCharges_997.65  \
0                    0                    0                    0

   TotalCharges_997.75  TotalCharges_998.1  TotalCharges_999.45  \
0                    0                   0                    0

   TotalCharges_999.8  TotalCharges_999.9  Churn
0                   0                   0      0

[1 rows x 6560 columns]
(80, 6559) (20, 6559) (80,) (20,)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
2026/02/01 03:27:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

LogisticRegression(max_iter=90)

/usr/local/lib/python3.12/dist-packages/mlflow/models/model.py:1209: FutureWarning: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization.The recommended safe alternative is the 'skops' format.
  flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)

In [ ]:
!python MLChurn/src/train.py

2026/02/01 03:39:12 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.schemas
2026/02/01 03:39:12 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.tables
2026/02/01 03:39:12 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.types
2026/02/01 03:39:12 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.constraints
2026/02/01 03:39:12 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.defaults
2026/02/01 03:39:12 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.comments
2026/02/01 03:39:13 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2026/02/01 03:39:13 INFO alembic.runtime.migration: Will assume non-transactional DDL.
Customer churn Classification
1
(100, 6560)
   SeniorCitizen  tenure  ...  TotalCharges_999.9  Churn
0              0       1  ...                   0      0

[1 rows x 6560 columns]
(80, 6559) (20, 6559) (80,) (20,)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
LogisticRegression(max_iter=50, penalty='l1', solver='saga')
2026/02/01 03:39:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
/usr/local/lib/python3.12/dist-packages/mlflow/models/model.py:1209: FutureWarning: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization.The recommended safe alternative is the 'skops' format.
  flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('myprojflow.db')

e = pd.read_sql_query('SELECT * FROM experiments',conn)
display(e)

m = pd.read_sql_query('SELECT * FROM metrics',conn)
display(m)

p = pd.read_sql_query('SELECT * FROM params',conn)
display(p)

lm = pd.read_sql_query("SELECT * FROM logged_models;", conn)
display(lm)

summ = pd.read_sql_query('''
  SELECT e.name, m.key, MAX(m.value), p.key, p.value, r.name, r.run_uuid
  FROM experiments e
  JOIN runs r on e.experiment_id = r.experiment_id
  JOIN metrics m on r.run_uuid = m.run_uuid AND m.key='f1_score'
  JOIN params p on r.run_uuid = p.run_uuid
  --WHERE #e.experiment_id = m.experiment_id AND e.experiment_id = p.experiment_id
  ''',conn)
display(summ)

summ = pd.read_sql_query('''
  SELECT e.name, m.key, MAX(m.value), p.key, p.value, r.name, r.run_uuid
  FROM experiments e
  JOIN runs r on e.experiment_id = r.experiment_id
  JOIN metrics m on r.run_uuid = m.run_uuid AND m.key='acc_score'
  JOIN params p on r.run_uuid = p.run_uuid
  --WHERE #e.experiment_id = m.experiment_id AND e.experiment_id = p.experiment_id
  ''',conn)

display(summ)

,experiment_id,name,artifact_location,lifecycle_stage,creation_time,last_update_time
0,0,Default,/content/mlruns/0,active,1769916385547,1769916385547
1,1,Customer churn Classification,/content/mlruns/1,active,1769916385566,1769916385566

,key,value,timestamp,run_uuid,step,is_nan
0,f1_score,0.666667,1769916464168,9832f0ac91a34a6db05d027b1a010c69,0,0
1,acc_score,0.800000,1769916464184,9832f0ac91a34a6db05d027b1a010c69,0,0
2,f1_score,0.666667,1769917154288,95b90ef535944d97884a39285c4dcd5e,0,0
3,acc_score,0.700000,1769917154305,95b90ef535944d97884a39285c4dcd5e,0,0

        key  value                          run_uuid
0     model  LR L2  9832f0ac91a34a6db05d027b1a010c69
1   penalty     l2  9832f0ac91a34a6db05d027b1a010c69
2  max_iter     90  9832f0ac91a34a6db05d027b1a010c69
3     model  LR L2  95b90ef535944d97884a39285c4dcd5e
4   penalty     l1  95b90ef535944d97884a39285c4dcd5e
5  max_iter     50  95b90ef535944d97884a39285c4dcd5e

,model_id,experiment_id,name,artifact_location,creation_timestamp_ms,last_updated_timestamp_ms,status,lifecycle_stage,model_type,source_run_id,status_message
0,m-adf846d2e44b41afb8ed480ae277bc8a,1,model,/content/mlruns/1/models/m-adf846d2e44b41afb8e...,1769916464223,1769916471895,2,active,None,9832f0ac91a34a6db05d027b1a010c69,None
1,m-c588f44a0707471a9cc1befcc9303ba7,1,model,/content/mlruns/1/models/m-c588f44a0707471a9cc...,1769917154348,1769917160848,2,active,None,95b90ef535944d97884a39285c4dcd5e,None

,name,key,MAX(m.value),key,value,name,run_uuid
0,Customer churn Classification,f1_score,0.666667,model,LR L2,LR L2,9832f0ac91a34a6db05d027b1a010c69

,name,key,MAX(m.value),key,value,name,run_uuid
0,Customer churn Classification,acc_score,0.8,model,LR L2,LR L2,9832f0ac91a34a6db05d027b1a010c69